export { CompatViewElement } from './compat-view-element'
export { CompatControlPanelElement } from './control-panel-element'
export { CompatInspectorElement } from './inspector-element'
export { RecentResultItem } from './recent-result-item'
export { ResultsHistoryItem } from './results-history-item'