name: Build Shinkore

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./shinkore

jobs:
    clippy:
        runs-on: ubuntu-latest
        env:
            RUSTFLAGS: "-Dwarnings"

        steps:
          - uses: actions/checkout@v6
          - name: Run Clippy
            run: cargo clippy

    build:
        needs: clippy
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v6
          - name: Run Build Release
            run: cargo build -r
          - name: Run Tests
            run: cargo test