name: Build Shinkom

on:
    workflow_run:
        workflows: [Build Shinkore]
        branches: [master]
        types:
            - completed

jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                node-version: ["20.x", "25.x"]

        steps:
            - uses: actions/checkout@v6
            - name: Download WASM artifact
              uses: actions/download-artifact@v7
              with:
                name: shinkore-wasm
                path: pkg
                run-id: ${{ github.event.workflow_run.id }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - name: Run Build
              run: npm run build:js
            - name: Run Tests
              run: npm test
